name: test & apk

on:
  
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/debug/app-debug.aab

#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk


#  aab:
#    name: Generate Bundle
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v2
#        with:
#          java-version: 1.8
#
#      - name: Build debug Bundle
#        run: bash ./gradlew assembleDebug --stacktrace
#      - name: Upload aab
#        uses: actions/upload-artifact@v2
#        with:
#          name: bundle
#          path: app/build/outputs/bundle/debug/app-debug.aab
